name: lint

on: [pull_request]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/set-up-node@v2
        with:
          node-version: '20.10.0'
      - run: npm run lint 
      