name: lint

run-name: Basic validation of pull request

on: [pull_request]

jobs:
  run-lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
      - run: npm install
      - run: npm run lint
      